name: no_screenshot
description: Flutter plugin to enable, disable or toggle screenshot support in your application.
version: 0.2.1
homepage: https://flutterplaza.com
repository: https://github.com/FlutterPlaza/no_screenshot/releases/tag/v0.2.1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterplaza.no_screenshot
        pluginClass: NoScreenshotPlugin
      ios:
        pluginClass: NoScreenshotPlugin